// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/api.got
// DO NOT EDIT!
package template

import "bytes"

func FromApi(name, handler string, functions []string, req []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package api

import (
	"`)
	buffer.WriteString(name)
	buffer.WriteString(`/app/def"

	"github.com/gin-gonic/gin"
    "github.com/sunmi-OS/gocore/v2/api"
)

`)
	for k1, v1 := range functions {
		buffer.WriteString(`
    func `)
		buffer.WriteString(v1)
		buffer.WriteString(`(g *gin.Context) {
        ctx := api.NewContext(g)
        req := new(def.`)
		buffer.WriteString(req[k1])
		buffer.WriteString(`Request)
        err := ctx.BindValidator(req)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.Success(def.`)
		buffer.WriteString(req[k1])
		buffer.WriteString(`Response{})
    }
`)
	}

}
