// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/api.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromApi(name, handler string, functions []string, req []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package api

import (
	"`)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`/app/domain"
	"`)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`/app/def"

	"github.com/gin-gonic/gin"
	"github.com/sunmi-OS/gocore/v2/api"
)`)

	for k1, v1 := range functions {
		buffer.WriteString(`
    func `)
		hero.EscapeHTML(v1, buffer)
		buffer.WriteString(`(g *gin.Context) {
    ctx := api.NewContext(g)
	req := &def.`)
		hero.EscapeHTML(req[k1], buffer)
		buffer.WriteString(`Request{}
		err := ctx.BindValidator(req)
		if err != nil {
			ctx.Error(err)
			return
		}
        response, err := domain.`)
		hero.EscapeHTML(v1, buffer)
		buffer.WriteString(`(req,ctx)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.Success(response)
}
`)
	}

}
