// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/api_request.got
// DO NOT EDIT!
package template

import "bytes"

func FromApiRequest(request, params string, buffer *bytes.Buffer) {
	buffer.WriteString(`

type `)
	buffer.WriteString(request)
	buffer.WriteString(` struct {
    `)
	buffer.WriteString(params)
	buffer.WriteString(`
}`)

}
