// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/api_request.got
// DO NOT EDIT!
package template

import (
	"bytes"
)

func FromApiRequest(request, params string, buffer *bytes.Buffer) {
	buffer.WriteString(`

type `)
	buffer.WriteString(request)
	buffer.WriteString(` struct {
    `)
	buffer.WriteString(params)
	buffer.WriteString(`
}`)

}
