// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/cmd_job.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromCmdJob(name, jobCmd, jobFunctions string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package cmd

import (
	"`)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`/app/job"
	"`)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`/common"

	"github.com/urfave/cli"
)

// Job cmd 任务相关
var Job = cli.Command{
	Name:    "job",
	Aliases: []string{"j"},
	Usage:   "job",
	Subcommands: []cli.Command{
		`)
	hero.EscapeHTML(jobCmd, buffer)
	buffer.WriteString(`
	},
}
`)
	hero.EscapeHTML(jobFunctions, buffer)

}
