// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/conf_const.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"strings"

	"github.com/shiyanhui/hero"
)

func FromConfConst(projectName string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package conf

const (
	ProjectName    = "`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`"
	ProjectVersion = "v1.0.0"
`)
	mysqlMap := goCoreConfig.Config.CMysql
	for _, v1 := range mysqlMap {
		buffer.WriteString(`DB` + strings.Title(v1.Name) + `          = "` + `db` + strings.Title(v1.Name) + `"
		`)
	}

	for _, v1 := range goCoreConfig.Config.CRedis {
		for k2 := range v1.Index {
			buffer.WriteString(strings.Title(v1.Name) + strings.Title(k2) + "Redis = \"" + v1.Name + "." + k2 + "\"\n")
		}
	}

	buffer.WriteString(`)`)

}
