// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/conf_local.got
// DO NOT EDIT!
package template

import "bytes"

func FromConfLocal(env, content string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package conf

var `)
	buffer.WriteString(env)
	buffer.WriteString(` = ` + "`" + ``)
	buffer.WriteString(content)
	buffer.WriteString(`
` + "`" + `

`)

}
