// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/conf_local.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromConfLocal(content string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package conf

var localConfig = ` + "`" + ``)
	hero.EscapeHTML(content, buffer)
	buffer.WriteString(`` + "`" + ``)

}
