// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/conf_mysql.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"strings"

	"github.com/shiyanhui/hero"
)

func FromConfMysql(dbName string, buffer *bytes.Buffer) {
	buffer.WriteString(`
[db`)
	hero.EscapeHTML(strings.Title(dbName), buffer)
	buffer.WriteString(`]
dbHost = ""           #数据库连接地址
dbName = "`)
	hero.EscapeHTML(dbName, buffer)
	buffer.WriteString(`` + "`" + ` + dbName + ` + "`" + `"           #数据库名称
dbUser = ""           #数据库用户名
dbPasswd = ""         #数据库密码
dbPort = "3306"       #数据库端口号
dbOpenconns_max = 20  #最大连接数
dbIdleconns_max = 20  #最大空闲连接
dbType = "mysql"`)

}
