// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/conf_base.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromConfBase(buffer *bytes.Buffer) {
	buffer.WriteString(`
package conf

var baseConfig = ` + "`" + `
[network]
ApiServiceHost = "`)
	hero.EscapeHTML(goCoreConfig.HttpApis.Host, buffer)
	buffer.WriteString(`"
ApiServicePort = "`)
	hero.EscapeHTML(goCoreConfig.HttpApis.Port, buffer)
	buffer.WriteString(`"
` + "`" + ``)

}
