// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/conf_const.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromConfConst(projectName string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package conf

const (
	PROJECT_NAME      = "`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`"
	PROJECT_VERSION   = "v1.0.0"
)`)

}
