// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/cronjob.got
// DO NOT EDIT!
package template

import "bytes"

func FromCronJob(cron string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package cronjob
// `)
	buffer.WriteString(cron)
	buffer.WriteString(`
func `)
	buffer.WriteString(cron)
	buffer.WriteString(`() {
}`)

}
