// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/domain.got
// DO NOT EDIT!
package template

import "bytes"

func FromDomain(buffer *bytes.Buffer) {
	buffer.WriteString(`
package domain
`)

}
