// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/domain_handler.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromDomainHandler(handlers []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package domain
`)
	for _, v1 := range handlers {
		buffer.WriteString(`
    var `)
		hero.EscapeHTML(v1, buffer)
		buffer.WriteString(`Handler = &`)
		hero.EscapeHTML(v1, buffer)
		buffer.WriteString(`{}
    type `)
		hero.EscapeHTML(v1, buffer)
		buffer.WriteString(` struct{}
`)
	}

}
