// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/domain.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromDomain(name, handler, function, req string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package domain

import (
	"`)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`/app/def"
)

// `)
	hero.EscapeHTML(function, buffer)
	buffer.WriteString(`
func (this *`)
	hero.EscapeHTML(handler, buffer)
	buffer.WriteString(`) `)
	hero.EscapeHTML(function, buffer)
	buffer.WriteString(`(req * def.`)
	hero.EscapeHTML(req, buffer)
	buffer.WriteString(`) (map[string]interface{}, int, error) {
	return map[string]interface{}{}, 1, nil
}`)

}
