// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/job.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromJob(job string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package job
// `)
	hero.EscapeHTML(job, buffer)
	buffer.WriteString(`
func `)
	hero.EscapeHTML(job, buffer)
	buffer.WriteString(`() {
}
`)

}
