// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/job.got
// DO NOT EDIT!
package template

import "bytes"

func FromJob(job string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package job
// `)
	buffer.WriteString(job)
	buffer.WriteString(`
func `)
	buffer.WriteString(job)
	buffer.WriteString(`() {
}
`)

}
