// Code generated by hero.
// source: /Users/SM0286/code/core/gocore/tools/gocore/template/main.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromMain(projectName string, cmdList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package main

import (
	"log"
	"os"

	"`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`/cmd"
	"`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`/common"

    "github.com/urfave/cli"
	gocoreLog "github.com/sunmi-OS/gocore/v2/utils/log"
)

func main() {
	// 配置cli参数
	app := cli.NewApp()
	app.Name = common.PROJECT_NAME
	app.Usage = common.PROJECT_NAME
	app.Email = ""
	app.Version = common.PROJECT_VERSION

	// 指定命令运行的函数
	app.Commands = []cli.Command{
        `)
	for _, cmd := range cmdList {
		hero.EscapeHTML(cmd, buffer)
	}
	buffer.WriteString(`
	}

	//初始化log
	gocoreLog.InitLogger(common.PROJECT_NAME)

	// 启动cli
	if err := app.Run(os.Args); err != nil {
		log.Fatalf("Failed to start application: %v", err)
	}
}`)

}
