// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/main.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromMain(projectName string, cmdList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package main

import (
	"os"

	"`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`/cmd"
	"`)
	hero.EscapeHTML(projectName, buffer)
	buffer.WriteString(`/conf"

	"github.com/sunmi-OS/gocore/v2/glog"
	"github.com/sunmi-OS/gocore/v2/utils"
	"github.com/urfave/cli/v2"
)

func main() {
	// 打印Banner
	utils.PrintBanner(conf.ProjectName` + "`" + `)
	// 配置cli参数
	app := cli.NewApp()
	app.Name = conf.ProjectName
	app.Usage = conf.ProjectName
	app.Version = conf.ProjectVersion

	// 指定命令运行的函数
	app.Commands = []*cli.Command{
        `)
	for _, cmd := range cmdList {
		hero.EscapeHTML(cmd, buffer)
	}
	buffer.WriteString(`
	}

	// 启动cli
	if err := app.Run(os.Args); err != nil {
		glog.ErrorF("Failed to start application: %v", err)
	}
}`)

}
