// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/model_table.got
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func FromModelTable(dbName, tableStruct, tableName, fields string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package `)
	hero.EscapeHTML(dbName, buffer)
	buffer.WriteString(`

import (
	gormx "gorm.io/gorm"
)

var `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`Handler = &`)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`{}

type `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(` struct {
	`)
	hero.EscapeHTML(fields, buffer)
	buffer.WriteString(`
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) Insert(db *gormx.DB, data * `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) error {
	if db == nil {
		db = Orm()
	}
	return db.Create(data).Error
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) BatchInsert(db *gormx.DB, data []* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) error {
	if db == nil {
		db = Orm()
	}
	return db.Create(&data).Error
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) GetOne(where string, args ...interface{}) (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`, error) {
	var obj `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`
	return &obj, Orm().Where(where, args...).Take(&obj).Error
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) GetList(where string, args ...interface{}) ([]* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`, error) {
	var list []*`)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`
	db := Orm()
	return list, db.Where(where, args...).Find(&list).Error
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) GetCount(where string, args ...interface{}) (int, error) {
	var number int
	err := Orm().Model(&`)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`{}).Where(where, args...).Count(&number).Error
	return number, err
}

func (* `)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) Delete(db *gormx.DB, where string, args ...interface{}) error {
	if db == nil {
		db = Orm()
	}
	return db.Where(where, args...).Delete(&`)
	hero.EscapeHTML(dbName, buffer)
	buffer.WriteString(`` + "`" + ` + tableStruct + ` + "`" + `{}).Error
}

func (*`)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`) Update(db *gormx.DB, data map[string]interface{}, where string, args ...interface{}) (int64, error) {
	if db == nil {
		db = Orm()
	}
	db = db.Model(&`)
	hero.EscapeHTML(tableStruct, buffer)
	buffer.WriteString(`{}).Where(where, args...).Updates(data)
	return db.RowsAffected, db.Error
}`)

}
