// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/model.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"strings"
)

func FromModel(dbName, tabels string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package `)
	buffer.WriteString(dbName)
	buffer.WriteString(`

import (
	"fmt"

	"`)
	buffer.WriteString(goCoreConfig.Service.ProjectName)
	buffer.WriteString(`/conf"
	"gorm.io/gorm"
	g "github.com/sunmi-OS/gocore/v2/db/orm"
	"github.com/sunmi-OS/gocore/v2/utils"
)

func Orm() *gorm.DB {
	db := g.GetORM(conf.DB`)
	buffer.WriteString(strings.Title(dbName))
	buffer.WriteString(`)
	if utils.GetRunTime() != "onl" {
		db = db.Debug()
	}
	return db
}

func SchemaMigrate() {
	fmt.Println("开始初始化`)
	buffer.WriteString(dbName)
	buffer.WriteString(`数据库")
	//自动建表，数据迁移
    `)
	buffer.WriteString(tabels)
	buffer.WriteString(`
	fmt.Println("数据库`)
	buffer.WriteString(dbName)
	buffer.WriteString(`初始化完成")
}`)

}
