// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apitest/hello.proto

package apitest

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

type CreateHelloReq struct {
}

type CreateHelloResp struct {
}

type UpdateHelloReq struct {
}

type UpdateHelloResp struct {
}

type DeleteHelloReq struct {
}

type DeleteHelloResp struct {
}

type GetHelloReq struct {
}

type GetHelloResp struct {
}

type ListHelloReq struct {
}

type ListHelloResp struct {
}
