// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: apitest/hello.proto

package apitest

import (
	sonic "github.com/bytedance/sonic"
)

func (m *CreateHelloReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreateHelloReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreateHelloReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreateHelloReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *CreateHelloResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreateHelloResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreateHelloResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreateHelloResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *UpdateHelloReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *UpdateHelloReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *UpdateHelloReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *UpdateHelloReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *UpdateHelloResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *UpdateHelloResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *UpdateHelloResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *UpdateHelloResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *DeleteHelloReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *DeleteHelloReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *DeleteHelloReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *DeleteHelloReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *DeleteHelloResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *DeleteHelloResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *DeleteHelloResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *DeleteHelloResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetHelloReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetHelloReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetHelloReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetHelloReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetHelloResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetHelloResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetHelloResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetHelloResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ListHelloReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ListHelloReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ListHelloReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ListHelloReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ListHelloResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ListHelloResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ListHelloResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ListHelloResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}
